# Use envFrom to load Secrets and ConfigMaps into environment variables

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: prussia-test-pod
  labels:
    app: prussia-test-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prussia-test-pod
  template:
    metadata:
      labels:
        app: prussia-test-pod
    spec:
      containers:
        - name: app
          image: k8s.gcr.io/busybox
          command: [ "/bin/sh", "-c", "env" ]
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: env-configmap
          - secretRef:
              name: env-secrets